# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex

build:
  script:
    - apt install python3-pip texlive-xetex texlive-latex-extra pandoc wget unzip
    - wget https://github.com/rsms/inter/releases/download/v3.15/Inter-3.15.zip
    - mkdir -p ~/.local/share/fonts
    - unzip Inter-3.15.zip
    - mv 'Inter Desktop' ~/.local/share/fonts/
    - fc-cache ~/.local/share/fonts
    - pip3 install sphinx
    - cd src/source
    - ./build-pdf-book.sh
  artifacts:
    paths:
      - "build/*.pdf"
